name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release
  BUNDLE_ID: com.mach1.notepad
  VERSION: 1.0.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest, windows-2016]

    steps:
    - uses: actions/checkout@v3

    - name: Submodule JUCE
      uses: actions/checkout@v3
      with:
        repository: juce-framework/JUCE
        path: JUCE
        ref: '6.1.6'

    - name: Submodule JUCE_deps
      uses: actions/checkout@v3
      with:
        repository: Mach1Studios/m1-juce-deps
        path: JUCE_deps
        token: ${{ secrets.CI_PAT }}
        lfs: true
    
    - name: LFS pull submodule
      run: |
        git -C JUCE_deps lfs pull
        ls -R JUCE_deps

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake (macos)
      if: runner.os == 'MacOS'
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Configure CMake (windows)
      if: runner.os == 'Windows'
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Codesign AAX (macos)
      if: runner.os == 'MacOS'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      env:
        DIST_DIR: ${{runner.workspace}}/build/M1-Notepad_artefacts/Release
        WRAPTOOL_MAC: ${{ secrets.WRAPTOOL_MAC }}
        PACE_ID: ${{ secrets.PACE_ID }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        M1_GLOBAL_GUID: ${{ secrets.M1_GLOBAL_GUID }}
      run: |
        ${{runner.workspace}}/JUCE_deps/${WRAPTOOL_MAC} wrap --verbose --account ${PACE_ID} --wcguid ${M1_GLOBAL_GUID} --signid ${APPLE_ID} --fusion off --installedbinaries --in ${DIST_DIR}/AAX/M1-NotePad.aaxplugin --out ${DIST_DIR}/AAX/M1-NotePad.aaxplugin

    - name: Codesign AAX (windows)
      if: runner.os == 'Windows'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      env:
        DIST_DIR: ${{runner.workspace}}/build/M1-Notepad_artefacts/Release
        WRAPTOOL_WIN: ${{ secrets.WRAPTOOL_WIN }}
        PACE_ID: ${{ secrets.PACE_ID }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        M1_GLOBAL_GUID: ${{ secrets.M1_GLOBAL_GUID }}
      run: |
        ${{runner.workspace}}/JUCE_deps/${WRAPTOOL_WIN} wrap --verbose --account ${PACE_ID} --wcguid ${M1_GLOBAL_GUID} --signid ${APPLE_ID} --fusion off --in ${DIST_DIR}/AAX/M1-NotePad.aaxplugin --out ${DIST_DIR}/AAX/M1-NotePad.aaxplugin

    - name: Package (macos)
      if: runner.os == 'MacOS'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      env:
        DIST_DIR: ${{runner.workspace}}/build/M1-Notepad_artefacts/Release
        INSTALL_DIR: /Library/Audio/Plug-Ins
        AAX_INSTALL_DIR: /Library/Application\ Support/Avid/Audio/Plug-Ins
        BUNDLE_ID: ${{ env.BUNDLE_ID }}
        VERSION: ${{ env.VERSION }}
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_INSTALLER_CERT: ${{ secrets.MACOS_INSTALLER_CERT }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        echo $MACOS_INSTALLER_CERT | base64 --decode > installer.p12
        RANDOM_PWD=`date | md5`
        security create-keychain -p ${RANDOM_PWD} build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p ${RANDOM_PWD} build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security import installer.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/productbuild
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${RANDOM_PWD} build.keychain
        /usr/bin/codesign --timestamp --force --deep -s "Developer ID Application" ${DIST_DIR}/AU/M1-Notepad.component -v
        /usr/bin/codesign --timestamp --force --deep -s "Developer ID Application" ${DIST_DIR}/VST3/M1-Notepad.vst3 -v
        /usr/bin/codesign --timestamp --force --deep -s "Developer ID Application" ${DIST_DIR}/AAX/M1-Notepad.aaxplugin -v
        pkgbuild --identifier ${BUNDLE_ID}.au --version ${VERSION} --component ${DIST_DIR}/AU/M1-Notepad.component \
        --install-location "${INSTALL_DIR}/Components" ${DIST_DIR}/M1-Notepad.au.pkg 
        pkgbuild --identifier ${BUNDLE_ID}.vst3 --version ${VERSION} --component ${DIST_DIR}/VST3/M1-Notepad.vst3 \
        --install-location "${INSTALL_DIR}/VST3" ${DIST_DIR}/M1-Notepad.vst3.pkg 
        pkgbuild --identifier ${BUNDLE_ID}.aaxplugin --version ${VERSION} --component ${DIST_DIR}/AAX/M1-Notepad.aaxplugin \
        --install-location "${AAX_INSTALL_DIR}" ${DIST_DIR}/M1-Notepad.aaxplugin.pkg 
        productbuild --synthesize \
        --package "${DIST_DIR}/M1-Notepad.au.pkg" \
        --package "${DIST_DIR}/M1-Notepad.vst3.pkg" \
        --package "${DIST_DIR}/M1-Notepad.aaxplugin.pkg" \
        distribution.xml
        productbuild --sign "Developer ID Installer" --distribution distribution.xml --package-path ${DIST_DIR} ${DIST_DIR}/M1-Notepad.pkg
    
    - name: Notarize (macos)
      if: runner.os == 'MacOS'
      uses: devbotsxyz/xcode-notarize@v1
      with:
        product-path: "${{runner.workspace}}/build/M1-Notepad_artefacts/Release/M1-Notepad.pkg"
        appstore-connect-username: ${{ secrets.MACOS_NOTARIZE_USER }} 
        appstore-connect-password: ${{ secrets.MACOS_NOTARIZE_PWD }} 
        primary-bundle-id: ${{ env.BUNDLE_ID }}

    - name: Staple (macos)
      if: runner.os == 'MacOS'
      uses: devbotsxyz/xcode-staple@v1
      with:
        product-path: "${{runner.workspace}}/build/M1-Notepad_artefacts/Release/M1-Notepad.pkg"

    - name: InnoSetup Installer (windows)
      if: runner.os == 'Windows'
      working-directory: ${{runner.workspace}}/build
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" /DBuildDir="${{runner.workspace}}\build\M1-Notepad_artefacts\Release" "${{runner.workspace}}\M1-Notepad\Resources\InnoSetup.iss"
      shell: cmd

    - name: 'Upload Artifact (macos)'
      if: runner.os == 'MacOS'
      uses: actions/upload-artifact@v2
      with:
        name: M1-Notepad (MacOS)
        path: ${{runner.workspace}}/build/M1-Notepad_artefacts/Release/M1-Notepad.pkg
        if-no-files-found: error

    - name: 'Upload Artifact (windows)'
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: M1-Notepad (Windows)
        path: ${{runner.workspace}}\build\M1-Notepad_artefacts\Release\Output\M1-Notepad_WIN.exe
        if-no-files-found: error